/** Public design-engineering tool directory. Generated by scripts/sync.mjs. */
import rawCatalog from '../catalog.json';

export interface ToolEntry {
  name: string;
  url: string;
  /** 同步时下载到 public 的 favicon。 */
  icon: string | null;
}

export interface ToolCategory {
  /** Stable source heading used for filtering and synchronization. */
  id: string;
  tools: ToolEntry[];
}

export interface ToolCatalog {
  sourceUrl: string;
  syncedAt: string;
  categories: ToolCategory[];
}

export const toolCatalog = rawCatalog as ToolCatalog;
export const toolCategories = toolCatalog.categories;
export const toolCategoryCount = toolCategories.length;
export const tools = toolCategories.flatMap((category) =>
  category.tools.map((tool) => ({ ...tool, category: category.id })),
);
export const toolCount = tools.length;

/** A compact, varied live-content preview for the portfolio timeline. */
export const toolPreview = toolCategories
  .slice(0, 4)
  .flatMap((category) =>
    category.tools.slice(0, 1).map((tool) => ({ ...tool, category: category.id })),
  );
